// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	hwcloudvpc "demo/internal/handler/hwcloud/vpc"
	"demo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/from/:name",
				Handler: DemoHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/vpc/all",
				Handler: hwcloudvpc.VpcGetAllHandler(serverCtx),
			},
		},
		rest.WithPrefix("/cloud/hw/v1"),
	)
}
